US7.1.1 add supplier payment
WildCodeSchool/purple-php-2109-project3-destinations-and-adventures pull request #21
Opened 2022-01-05 15:22 UTC by alexandregrue

2022-01-05 16:17 UTC, soufcod3 approved these changes
Nothing much to say

2022-01-06 07:50 UTC, RomainClair requested changes
Migration files are not consisten with dev ones

2022-01-06 08:44 UTC, soufcod3 approved these changes
The new version file looks alright

2022-01-06 11:25 UTC, RomainClair approved these changes

2022-01-06 11:25 UTC, merged