US7.2 Edit supplier information
WildCodeSchool/purple-php-2109-project3-destinations-and-adventures pull request #30
Opened 2022-01-11 16:05 UTC by alexandregrue

…and make link in new to edit resolve problem with proprety in booking entity

2022-01-12 10:10 UTC, soufcod3 submitted a review, later dismissed

2022-01-13 14:38 UTC, FouziaAs approved these changes

2022-01-13 15:48 UTC, RomainClair requested changes
It seems that this PR changes the entities, so it should embed the associated migrations and may be fixtures

2022-01-14 10:43 UTC, RomainClair approved these changes

2022-01-14 10:44 UTC, merged