create edit function for client
WildCodeSchool/purple-php-2109-project3-destinations-and-adventures pull request #35
Opened 2022-01-12 10:12 UTC by alexandregrue

2022-01-12 10:51 UTC, soufcod3 submitted a review, later dismissed

2022-01-13 14:40 UTC, FouziaAs submitted a review, later dismissed

2022-01-13 15:50 UTC, RomainClair requested changes

2022-01-13 15:50 UTC, RomainClair commented on src/Controller/ClientController.php
> +            'client' => $client,
You probably don't need the client in your view

2022-01-14 08:35 UTC, iStyyx submitted a review, later dismissed

2022-01-14 09:55 UTC, iStyyx approved these changes

2022-01-14 10:45 UTC, RomainClair approved these changes

2022-01-14 10:45 UTC, merged