add a new booking
WildCodeSchool/purple-php-2109-project3-destinations-and-adventures pull request #8
Opened 2021-12-25 19:03 UTC by soufcod3

2022-01-03 08:21 UTC, mcbeloy approved these changes

2022-01-03 09:29 UTC, mcbeloy approved these changes

2022-01-03 09:29 UTC, FouziaAs submitted a review, later dismissed

2022-01-03 09:29 UTC, FouziaAs commented
ok

2022-01-03 11:15 UTC, RomainClair requested changes
As the GeneralInfoType is used to fill a Booking entity, you should have Constraints in Booking to validate your input.
You could use IntegerType instead of TextType for numeric values

There's no validation either for Client (filled by the ClientType) and Agent (filled via AgentType)

2022-01-03 11:15 UTC, RomainClair commented on src/Controller/GeneralInfoController.php
> +            return $this->redirectToRoute('booking_index');
The booking_index route does not exists

2022-01-03 15:41 UTC, iStyyx approved these changes
Looks better

2022-01-04 13:08 UTC, RomainClair requested changes
The migration file is incoherent with the database as it is in the dev branch

2022-01-05 09:00 UTC, mcbeloy approved these changes

2022-01-05 09:00 UTC, mcbeloy commented
It's good

2022-01-05 09:01 UTC, mcbeloy approved these changes

2022-01-05 15:31 UTC, RomainClair approved these changes

2022-01-05 15:31 UTC, merged